export function downloadFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportResultAsMarkdown(title: string, output: string): void {
  const content = `# ${title}\n\n_Generated by OmniAgent Enterprise_\n\n---\n\n${output}\n`;
  downloadFile(`${title.replace(/\s+/g, '_').toLowerCase()}.md`, content, 'text/markdown');
}

export function exportResultAsJson(result: Record<string, unknown>): void {
  downloadFile('omniagent_result.json', JSON.stringify(result, null, 2), 'application/json');
}
